### ISSUE TITLE
对这个respository的一点小提议

### ISSUE THREAD

**Issue by zmc-x** [Lyfive/HnusterComputer#1]
**`ffj`可以去搞一个HNUST计算机专业的课程共享计划，感觉挺好的**

**Comment by Lyfive** [comment]
不知道共享计划是什么样的形式，考后可以交流一下。

**Comment by zmc-x** [comment]
> 不知道共享计划是什么样的形式，考后可以交流一下。

**Comment by zmc-x** [comment]
对于这个可以参考这个[清华大学课程共享计划](https://github.com/PKUanonym/REKCARC-TSC-UHT)
