### ISSUE TITLE
数据库笔记中 union字打错了

### ISSUE THREAD

**Issue by 3210448723** [Lyfive/HnusterComputer#5]
1. unique（并）->1. union（并）

**Comment by Lyfive** [comment]
已修正，谢谢

**Comment by 3210448723** [comment]
补充
419行
revoke all privilegews -> revoke all privileges
501
也部分依赖于码。 -> 也不部分依赖于码。
623
日志文件是用来就事务对数据库的更新操作的文件。 -> 日志文件是用来记录事务对数据库的更新操作的文件。

**Comment by Lyfive** [comment]
已修正
